version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  elasticsearch:
    image: "elasticsearch:latest"
    ports:
      - "9200:9200"
      - "9300:9300"
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"